name: 'Module Runner'
description: 'Runs module-specific actions dynamically'

inputs:
  module:
    description: 'Module name'
    required: true
  action:
    description: 'Action to run (validate, test, security)'
    required: true
  terraform-version:
    description: 'Terraform version'
    required: false
    default: '1.10.3'
  github-token:
    description: 'GitHub token for security scan'
    required: false
  azure-credentials:
    description: 'Azure credentials for testing'
    required: false

outputs:
  tfsec-sarif:
    description: 'Path to tfsec SARIF file'
    value: ${{ steps.run-action.outputs.tfsec-sarif }}
  checkov-sarif:
    description: 'Path to Checkov SARIF file'
    value: ${{ steps.run-action.outputs.checkov-sarif }}

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false
    
    - name: Make script executable
      shell: bash
      run: chmod +x .github/actions/module-runner/run-module-action.sh
    
    - name: Run module action
      id: run-action
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        AZURE_CREDENTIALS: ${{ inputs.azure-credentials }}
      run: |
        .github/actions/module-runner/run-module-action.sh "${{ inputs.module }}" "${{ inputs.action }}" "${{ inputs.terraform-version }}"
    
    - name: Upload tfsec SARIF
      if: ${{ inputs.action == 'security' && steps.run-action.outputs.tfsec-sarif != '' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.run-action.outputs.tfsec-sarif }}
        category: tfsec-${{ inputs.module }}
      continue-on-error: true
    
    - name: Upload Checkov SARIF
      if: ${{ inputs.action == 'security' && steps.run-action.outputs.checkov-sarif != '' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.run-action.outputs.checkov-sarif }}
        category: checkov-${{ inputs.module }}
      continue-on-error: true