name: 'Module Runner'
description: 'Runs module-specific actions dynamically'

inputs:
  module:
    description: 'Module name'
    required: true
  action:
    description: 'Action to run (validate, test, security)'
    required: true
  terraform-version:
    description: 'Terraform version'
    required: false
    default: '1.10.3'
  github-token:
    description: 'GitHub token for security scan'
    required: false
  azure-credentials:
    description: 'Azure credentials for testing'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false
    
    - name: Check if module action exists
      id: check
      shell: bash
      run: |
        ACTION_PATH="modules/${{ inputs.module }}/.github/actions/${{ inputs.action }}/action.yml"
        if [[ -f "$ACTION_PATH" ]]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Action found: $ACTION_PATH"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Action not found: $ACTION_PATH"
        fi

    - name: Run module-specific action
      if: steps.check.outputs.exists == 'true'
      uses: ./modules/${{ inputs.module }}/.github/actions/${{ inputs.action }}
      with:
        terraform-version: ${{ inputs.terraform-version }}
        github-token: ${{ inputs.github-token }}
        azure-credentials: ${{ inputs.azure-credentials }}

    - name: Fallback for missing action
      if: steps.check.outputs.exists == 'false'
      shell: bash
      run: |
        echo "::warning::No ${{ inputs.action }} action found for module ${{ inputs.module }}"
        echo "Module-specific action not implemented yet. Skipping..."