#!/bin/bash
# Azure DevOps credentials for testing (set real values before running integration tests)
export AZDO_ORG_SERVICE_URL="https://dev.azure.com/YOUR_ORG_HERE"
export AZDO_PERSONAL_ACCESS_TOKEN="YOUR_PAT_HERE"
export AZDO_PROJECT_ID="YOUR_PROJECT_ID_HERE"

# Identity IDs for each test scenario (use distinct identities to avoid conflicts)
export AZDO_SECURITYROLE_ASSIGNMENT_IDENTITY_ID_BASIC="YOUR_IDENTITY_ID_BASIC"
export AZDO_SECURITYROLE_ASSIGNMENT_IDENTITY_ID_COMPLETE="YOUR_IDENTITY_ID_COMPLETE"
export AZDO_SECURITYROLE_ASSIGNMENT_IDENTITY_ID_SECURE="YOUR_IDENTITY_ID_SECURE"

# Optional: scope IDs for security role assignments (defaults to AZDO_PROJECT_ID)
export AZDO_SECURITYROLE_ASSIGNMENT_SCOPE_ID_BASIC="YOUR_SCOPE_ID_BASIC"
export AZDO_SECURITYROLE_ASSIGNMENT_SCOPE_ID_COMPLETE="YOUR_SCOPE_ID_COMPLETE"
export AZDO_SECURITYROLE_ASSIGNMENT_SCOPE_ID_SECURE="YOUR_SCOPE_ID_SECURE"

# Optional: resource IDs for security role assignments (defaults to AZDO_PROJECT_ID)
export AZDO_SECURITYROLE_ASSIGNMENT_RESOURCE_ID_BASIC="YOUR_RESOURCE_ID_BASIC"
export AZDO_SECURITYROLE_ASSIGNMENT_RESOURCE_ID_COMPLETE="YOUR_RESOURCE_ID_COMPLETE"
export AZDO_SECURITYROLE_ASSIGNMENT_RESOURCE_ID_SECURE="YOUR_RESOURCE_ID_SECURE"

echo "Azure DevOps credentials set for testing (placeholders)."
