# tfsec Configuration for Azure Terraform Modules
# This configuration enforces security best practices

# Minimum severity level
minimum_severity: LOW

# Exclude specific paths
exclude_paths:
  - .terraform/
  - "**/.terraform/"
  - "**/examples/"

# Custom checks path
custom_check_dir: ./security-policies/tfsec

# Include passed checks in output
include_passed: false

# Format for output
format: default

# Soft fail mode for CI/CD
# soft_fail: false

# Maximum severity to fail on
# max_severity: CRITICAL

# Specific Azure Storage checks to ensure are enabled:
# - azure-storage-default-action-deny
# - azure-storage-enforce-https
# - azure-storage-no-public-access
# - azure-storage-use-secure-tls-policy
# - azure-storage-queue-services-logging-enabled

# Exclude specific checks if needed (use sparingly)
# exclude:
#   - azure-storage-xxxxx

# Force all checks to run
force_all_checks: false

# Run statistical analysis
statistics: true

# Include ignored checks in output
include_ignored: true