formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Module Version

  Current version: **VERSION_PLACEHOLDER**

  ## Description

  MODULE_DESCRIPTION_PLACEHOLDER

  ## Usage

  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```

  ## Examples

  EXAMPLES_PLACEHOLDER

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Modules

  {{ .Modules }}

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

  ## Additional Documentation

  - [VERSIONING.md](VERSIONING.md) - Module versioning and release process
  - [SECURITY.md](SECURITY.md) - Security features and configuration guidelines

  {{ if .Config.Sections.Footer }}
  {{ .Footer }}
  {{ end }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true