# Test Configuration for MODULE_DISPLAY_NAME_PLACEHOLDER Module
test_config:
  module_name: "MODULE_NAME_PLACEHOLDER"
  module_type: "MODULE_TYPE_PLACEHOLDER"
  
  # Test environments
  environments:
    - name: "development"
      location: "West Europe"
      resource_group_prefix: "rg-test-dev"
    - name: "staging"
      location: "North Europe"
      resource_group_prefix: "rg-test-staging"
  
  # Test scenarios
  scenarios:
    basic:
      description: "Basic functionality test"
      terraform_dir: "../examples/basic"
      timeout: "30m"
      parallel: true
      
    complete:
      description: "Complete feature test"
      terraform_dir: "../examples/complete"
      timeout: "45m"
      parallel: true
      
    secure:
      description: "Security-focused test"
      terraform_dir: "../examples/secure"
      timeout: "45m"
      parallel: true
      
    private_endpoint:
      description: "Private endpoint test"
      terraform_dir: "../examples/private-endpoint"
      timeout: "60m"
      parallel: false
      
  # Performance test configuration
  performance:
    enabled: true
    timeout: "45m"
    concurrent_resources: 5
    
  # Integration test configuration
  integration:
    enabled: true
    cleanup: true
    timeout: "60m"
    
  # Resource naming
  naming:
    prefix: "MODULE_TYPE_PLACEHOLDERtest"
    max_length: 24
    allowed_chars: "abcdefghijklmnopqrstuvwxyz0123456789"
    
  # Test data
  test_data:
    locations:
      - "West Europe"
      - "North Europe"
      - "East US"
    
    tags:
      Environment: "Test"
      Module: "MODULE_NAME_PLACEHOLDER"
      ManagedBy: "Terraform"
      TestRun: "{{ .UniqueID }}"