formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Module Version

  Current version: **vUnreleased**

  ## Description

  This module creates a comprehensive Azure Storage Account with support for all enterprise features including security, monitoring, private endpoints, and lifecycle management.

  ## Usage

  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```

  ## Examples

    - [Advanced Policies](examples/advanced-policies) - This example demonstrates the implementation of advanced storage account policies including SAS policies, immutability policies, routing preferences, custom domains, and SMB configurations.
    - [Basic](examples/basic) - This example demonstrates a basic Azure Storage Account configuration using secure defaults and minimal setup.
    - [Complete](examples/complete) - This example demonstrates a comprehensive deployment of an Azure Storage Account with all available features and security configurations.
    - [Data Lake Gen2](examples/data-lake-gen2) - This example demonstrates how to configure an Azure Storage Account as a Data Lake Storage Gen2 with hierarchical namespace, SFTP, and NFSv3 support.
    - [Identity Access](examples/identity-access) - This example demonstrates how to configure an Azure Storage Account with **keyless authentication** using managed identities and Microsoft Entra ID (formerly Azure AD) integration. This approach eliminates the need for shared access keys, providing enhanced security through identity-based access control.
    - [Multi Region](examples/multi-region) - This example demonstrates a comprehensive multi-region Azure Storage Account deployment strategy with enhanced disaster recovery capabilities, cross-tenant replication, and optimized geo-redundancy configurations.
    - [Secure](examples/secure) - This example demonstrates a maximum-security Azure Storage Account configuration suitable for highly sensitive data and regulated environments.
    - [Secure Private Endpoint](examples/secure-private-endpoint) - This example demonstrates how to deploy a highly secure Azure Storage Account suitable for production environments handling sensitive data.
  
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Additional Documentation

  - [VERSIONING.md](VERSIONING.md) - Module versioning and release process
  - [SECURITY.md](SECURITY.md) - Security features and configuration guidelines

  {{ if .Config.Sections.Footer }}
  {{ .Footer }}
  {{ end }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true