formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Module Version

  Current version: **SAv1.0.0**

  ## Description

  {{ .Description }}

  ## Usage

  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```

  ## Examples

  - [Simple](examples/simple) - Basic storage account configuration
  - [Complete](examples/complete) - Full-featured storage account with all enterprise capabilities  
  - [Secure](examples/secure) - Maximum security configuration
  - [Multi-Region](examples/multi-region) - Multi-region setup with disaster recovery

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Modules

  {{ .Modules }}

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

  {{ if .Config.Sections.Footer }}
  {{ .Footer }}
  {{ end }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true