name: 🔒 Security Vulnerability
description: Report a security vulnerability (for non-critical issues only)
title: "[Security]: "
labels: ["security", "priority:high"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For critical security vulnerabilities, please DO NOT create a public issue.
        Instead, report them via GitHub Security Advisories or contact the maintainers directly.
        
        This template is for non-critical security improvements and best practice violations.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this security issue?
      options:
        - Low (best practice violation)
        - Medium (potential security risk)
        - High (security vulnerability)
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module has the security issue?
      options:
        - azurerm_storage_account
        - azurerm_virtual_network
        - azurerm_key_vault
        - azurerm_app_service
        - azurerm_sql_database
        - Multiple modules
        - Repository-wide
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue
      placeholder: |
        The module allows setting TLS version below 1.2...
        This could lead to...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: |
        This could allow attackers to...
        Affected users might experience...
    validations:
      required: true

  - type: textarea
    id: current-code
    attributes:
      label: Current Code
      description: Show the vulnerable code
      render: hcl
      placeholder: |
        # Current insecure default
        variable "min_tls_version" {
          default = "TLS1_0"
        }

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: How should this be fixed?
      render: hcl
      placeholder: |
        # Secure default
        variable "min_tls_version" {
          default = "TLS1_2"
        }

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a temporary workaround users can apply?
      placeholder: |
        Users can explicitly set min_tls_version = "TLS1_2" in their configuration

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: This is NOT a critical vulnerability requiring private disclosure
          required: true
        - label: I have checked if this issue already exists
          required: true
        - label: I have provided a suggested fix
          required: true