name: azurerm_storage_account
description: "Azure Storage Account Terraform module"
version: 1.0.0
terraform:
  required_version: ">= 1.5.0"
  required_providers:
    azurerm: ">= 3.0.0"
    random: ">= 3.1.0"
dependencies:
  - shared/terraform-lib
ci:
  test_regions:
    - westeurope
    - northeurope
  test_scenarios:
    - simple
    - secure
    - private-endpoint
    - multi-region
  performance_tests:
    enabled: true
    timeout: 45m
  integration_tests:
    enabled: true
    cleanup: true
release:
  versioning: semver
  changelog: keep-a-changelog
  tag_prefix: "azurerm_storage_account/v"
  protected_branches:
    - main
    - release/*
documentation:
  auto_generate: true
  include_examples: true
  include_tests: false