# Gemini Code Assist Configuration
have_fun: false  # Keep reviews professional
ignore_patterns:
  - "*.lock"
  - "dist/**"
  - "node_modules/**"
  - ".terraform/**"
  - "*.tfstate"
  - "*.tfstate.backup"
  - ".terraform.lock.hcl"
  - "coverage/**"
  - "*.log"
  
code_review:
  disable: false
  comment_severity_threshold: MEDIUM  # Focus on MEDIUM, HIGH, and CRITICAL issues
  max_review_comments: -1  # Unlimited comments for thorough review
  
# Additional settings for Terraform modules
review_focus:
  - security
  - best_practices
  - module_patterns
  - documentation