name: azurerm_virtual_network
description: "Manages Azure Virtual Network with comprehensive configuration options"
version: 1.0.0
terraform:
  required_version: ">= 1.3.0"
  required_providers:
    azurerm: ">= 4.35.0"
dependencies: []
ci:
  test_regions:
    - westeurope
    - northeurope
  test_scenarios:
    - basic
    - complete
    - secure
  performance_tests:
    enabled: true
    timeout: 45m
  integration_tests:
    enabled: true
    cleanup: true
release:
  versioning: semver
  changelog: keep-a-changelog
  tag_prefix: "VNv"
  protected_branches:
    - main
    - release/*
documentation:
  auto_generate: true
  include_examples: true
  include_tests: false