name: azurerm_virtual_network
display_name: "Virtual Network"
description: "Manages Azure Virtual Network with comprehensive configuration options including security features, peering, DNS integration, and monitoring"
category: "networking"
version: 1.0.0
terraform:
  required_version: ">= 1.3.0"
  required_providers:
    azurerm: "4.36.0"
dependencies: []
features:
  - "Virtual Network creation and management"
  - "DDoS protection plan integration"
  - "Virtual network peering"
  - "Private DNS zone links"
  - "Network flow logs and traffic analytics"
  - "Diagnostic settings and monitoring"
  - "Encryption enforcement"
  - "BGP community configuration"
ci:
  test_regions:
    - westeurope
    - northeurope
    - eastus2
  test_scenarios:
    - basic
    - complete
    - secure
    - private-endpoint
  performance_tests:
    enabled: true
    timeout: 45m
  integration_tests:
    enabled: true
    cleanup: true
    parallel: false
release:
  versioning: semver
  changelog: keep-a-changelog
  tag_prefix: "VNv"
  protected_branches:
    - main
    - release/*
documentation:
  auto_generate: true
  include_examples: true
  include_tests: false
  terraform_docs:
    enabled: true
    sort_by: "required"